### ISSUE TITLE
Setup failed

### ISSUE THREAD

**Issue by Boes24** [djerik/wavinsentio-ha#37]
Updatd to 5.2 and now it wont setup. 
<img width="925" height="669" alt="Image" src="https://github.com/user-attachments/assets/4f3f260a-f07e-45aa-81b0-969b7e18e098" />

**Comment by djerik** [comment]
I just released 0.5.3 to fix this. I believe this happens if you have never used Vacation Mode?

**Comment by Boes24** [comment]
Now I get this error.
I haven't used Vacation Mode before
<img width="940" height="236" alt="Image" src="https://github.com/user-attachments/assets/579ac612-e9d7-42ca-841f-26138e506a3e" />

**Comment by djerik** [comment]
Sorry for that - fix had a typo that got through my own testing as I cant reproduce with my own system. Please try 0.5.4

**Comment by smanf** [comment]
Still not working on 0.5.4.

![Image](https://github.com/user-attachments/assets/f3161cf2-7ca0-48f7-ab6c-950cf5618bbc)
